trigger:
  - main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install Dependencies with npm ci'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright and Dependencies'

- script: npx playwright test --output=playwright-report
  displayName: "Run Playwright Tests"
  env:
    CI: true

- script: dir playwright-report /s
  displayName: 'Debug Playwright Report Directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'playwright-report'
    ArtifactName: 'TestResults'
    publishLocation: 'Container'
  displayName: 'Publish Test Results as Artifacts'

- task: PublishTestResults@1
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: '**/junit-report*.xml'